### ISSUE TITLE
How to Clear the value of textboxio in angular js

### ISSUE THREAD

**Issue by Rajafkvp** [ephox/angular-textbox.io#1]

**Comment by mfromin** [comment]
Raj - 

When you say you want to "clear" the value my first instinct would be to simply highlight all the text and then delete it ... are you looking for something programmatic?  Can you provide more details as to what you are trying to accomplish?

**Comment by james4388** [comment]
After submit the form, I set the model to empty string `self.content = '';` but the text in editor still remain. How to clear it

**Comment by MichaelFromin** [comment]
Since Textbox.io is an HTML editor it has a different view of what "empty" is.  Try setting it to:

`<p>&nbsp;</p>`

...in my testing this clears out the editor but leaves it in a valid state for additional content creation.
