### ISSUE TITLE
HOW TO USE @MENTIONS IN textbox.Io

### ISSUE THREAD

**Issue by Rajafkvp** [ephox/angular-textbox.io#2]
![image](https://cloud.githubusercontent.com/assets/10266752/9553424/9d6fe9f2-4ddc-11e5-89e7-c5e2a1defdf7.png)

Textbox.Io

**Comment by mfromin** [comment]
Raj - 

Are you looking to implement @mentions as used in the OX App Suite?  Is that why you reference ox.io in your post?

**Comment by Rajafkvp** [comment]
No sorry ,I am looking for textbox.Io.

**Comment by mfromin** [comment]
Raj - 

@mentions is a "feature" of some applications (e.g. GitHub) - its not a core HTML feature so no rich text editor just "does" @mentions.  When you want to implement @mentions in any rich text editor you will need to understand the APIs that the application uses to implement @mentions.  If you look at this GitHub issue tracker when you type the '@' sign after a space a UI is invoked to allow you to select users in GitHub.  This is not "core" editor functionality but capability of the application.  

The RTE needs to have a trigger (e.g. typing the '@') and then invoke the application's APIs to fetch the list of users and then inject the appropriate HTML/JavaScript to make an "@mention" work.

**Comment by mfromin** [comment]
Raj - 

For some clarification Textbox.io will be able to address the "editor specific" parts of this (e.g. invoke some code after the '@' is pressed) in a future release.  I can't get into the specifics of this as its not something available today in Textbox.io.  If you have more interest on that part please open a support case at http://support.ephox.com as we would want to work with our customers to understand how such an API would be made public.

**Comment by Rajafkvp** [comment]
Ok mfromin Thanks..
