### ISSUE TITLE
Bug in validation

### ISSUE THREAD

**Issue by aximobile** [ephox/angular-textbox.io#6]
Hello,

We found a bug in the **tbio.js** directive.

Inside the **tbiController** is a loop that initializes all the validators. The problem is that this loop not only iterates over factory instance, but also over the **prototype properties** of the factory object.

Following lines of code:
`          for (var validationFn in tbioValidationsFactory) {
              $log.log('Adding custom validation!');
              ngModelController.$validators[validationFn] = tbioValidationsFactory[validationFn];
          }`

Should be replaced by this:
`        
for (var validationFn in tbioValidationsFactory) {
          if (tbioValidationsFactory.hasOwnProperty(validationFn)) {
            $log.log('Adding custom validation!');
            ngModelController.$validators[validationFn] = tbioValidationsFactory[validationFn];
          }
        }
`

An extra check is needed to make sure that the **prototype properties** of the Factory object are not included inside this loop.

You can easily test this case by extending the factory prototype with a new property.

**Comment by tinydylan** [comment]
Apologies for the late reply. Per [this article](https://www.tiny.cloud/blog/the-future-of-textbox-io-and-rich-text-editing-solutions-from-tiny), Textbox.io is reaching end-of-life, and our efforts are going into TinyMCE.

I'd suggest looking at the [TinyMCE Angular Integration](https://github.com/tinymce/tinymce-angular/), which is being actively maintained.
