### ISSUE TITLE
Does the textbox.io supports angular 4-5 platforms

### ISSUE THREAD

**Issue by riginoommen** [ephox/angular-textbox.io#7]
If yes please share it

**Comment by drashti2277** [comment]
Any updates on this??

**Comment by riginoommen** [comment]
@drashti2277 - I think this project is not maintained 

[Angular Textbox IO](https://github.com/tinymce/angular-textbox.io) - FYI - https://docs.angularjs.org/misc/version-support-status

**Comment by tinydylan** [comment]
Apologies for the late reply. Per [this article](https://www.tiny.cloud/blog/the-future-of-textbox-io-and-rich-text-editing-solutions-from-tiny), Textbox.io is reaching end-of-life, and our efforts are going into TinyMCE.

I'd suggest looking at the [TinyMCE Angular Integration](https://github.com/tinymce/tinymce-angular/), which is being actively maintained.
